name: Release

on:
  push:
    tags:
      - 'v[0-9]*' # Matches v1, v1.0, v1.0.0, etc. (Prevents 'voldemort')

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Verify Version Match
        uses: okcodes/vump/.github/actions/check@main
        with:
          version: ${{ github.ref_name }}

      - uses: pnpm/setup@v2
        with:
          install: false

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '26'
          registry-url: 'https://registry.npmjs.org'

      - run: node -v
      - run: pnpm -v

      - name: Install Dependencies
        run: pnpm install

      - name: Publish to npm
        run: |
          ref="${GITHUB_REF_NAME,,}"
          if [[ "$ref" == *"alpha"* ]]; then
            pnpm publish --access public --no-git-checks --tag alpha
          elif [[ "$ref" == *"beta"* ]]; then
            pnpm publish --access public --no-git-checks --tag beta
          elif [[ "$ref" == *"rc"* ]]; then
            pnpm publish --access public --no-git-checks --tag rc
          else
            pnpm publish --access public --no-git-checks
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          VC_GIT_SHA: ${{ github.sha }}
